import './globals.css'
import { Montserrat } from 'next/font/google'
import AppBar from './AppBar'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Risk Test',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <AppBar/>
        {children}
      </body>
    </html>
  )
}
